### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by programmeres** [shalousun/api-doc-test#1]
现在的问题是通过你的doc-api-test直接生成后，这个请求参数的属性描述获取不到!!!!我查阅源码是qdox包的JavaField.getComment()方法取不到属性的注释，请快点看一下
以下是生成的markdown：
Parameter | Type|Description|Required
---|---|---|---
username|string|No comments found.|false
password|string|No comments found.|false
nickName|string|No comments found.|false
mobile|string|No comments found.|false

**Comment by shalousun** [comment]
根据你的描述，应该是你的这些字段的信息来自项目外的代码，你可以查看我们的文档通过加载外部的代码解决

**Comment by shalousun** [comment]
如果后续其它问题可以到https://github.com/shalousun/smart-doc项目下提，本项目仅作为提供测试使用
