### ISSUE TITLE
不能自定义请求的示例连接

### ISSUE THREAD

**Issue by bin1983** [shalousun/api-doc-test#2]
![image](https://user-images.githubusercontent.com/55977811/66808554-15031a80-ef5e-11e9-9b27-9e03cc6d0033.png)

**Comment by bin1983** [comment]
http://localhost:8088/action/api/v1/getTest?ym=0rb6n1
这个 ym 不能自定义

**Comment by netdied** [comment]
你说的是get请求的参数不能自定义么？ym=你的指定值？

**Comment by netdied** [comment]
> http://localhost:8088/action/api/v1/getTest?ym=0rb6n1
> 这个 ym 不能自定义
你是需要yml=你的指定值？而不是一个随机字符串？

**Comment by bin1983** [comment]
> > http://localhost:8088/action/api/v1/getTest?ym=0rb6n1
> > 这个 ym 不能自定义
> > 你是需要yml=你的指定值？而不是一个随机字符串？

是的 ym应该等于我自定义的值，而不是随机的字符串

**Comment by netdied** [comment]
> > > http://localhost:8088/action/api/v1/getTest?ym=0rb6n1
> > > 这个 ym 不能自定义
> > > 你是需要yml=你的指定值？而不是一个随机字符串？
> 
> 是的 ym应该等于我自定义的值，而不是随机的字符串

你不可能为你的每一个请求的参数设定默认值 decription里已经有了此参数的描述 前端是可以根据描述来构建链接

**Comment by bin1983** [comment]
> > > > http://localhost:8088/action/api/v1/getTest?ym=0rb6n1
> > > > 这个 ym 不能自定义
> > > > 你是需要yml=你的指定值？而不是一个随机字符串？
> > 
> > 
> > 是的 ym应该等于我自定义的值，而不是随机的字符串
> 
> 你不可能为你的每一个请求的参数设定默认值 decription里已经有了此参数的描述 前端是可以根据描述来构建链接

但是这样的话给用户的连接的样例就是错误的啊 ，用不了

**Comment by bin1983** [comment]
> > > > > > http://localhost:8088/action/api/v1/getTest?ym=0rb6n1
> > > > > > 这个 ym 不能自定义
> > > > > > 你是需要yml=你的指定值？而不是一个随机字符串？
> > > > 
> > > > 
> > > > 是的 ym应该等于我自定义的值，而不是随机的字符串
> > > 
> > > 
> > > 你不可能为你的每一个请求的参数设定默认值 decription里已经有了此参数的描述 前端是可以根据描述来构建链接
> > 
> > 
> > 但是这样的话给用户的连接的样例就是错误的啊 ，用不了
> 
> 目前你可以选择生成md之后再修改

嗯 先这么改吧 都生成好之后 在改

**Comment by shalousun** [comment]
已经支持，后去有问题请到smart-doc项目提，这个是针对国内用户提供的demo
